esphome_wifi_ssid: "ssid_here"
esphome_wifi_password: "password_here"
esphome_api_password: "another_password"
esphome_ota_password: "yet_another_password"
esphome_domain: ".local"

mqtt_broker_ip: "ip_here"

tile_daniel: "DE:AD:BE:EF:FE:ED"
tile_mariah: "DE:AD:BE:EF:FE:ED"
