---
esphome:
  name: dehumidifier_switch
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: -10
    then:
      - switch.turn_on: relay

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  domain: !secret esphome_domain

api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

binary_sensor:
  - platform: gpio
    name: "Dehumidifier Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: restart
    name: "Dehumidifier Switch Restart"
  - platform: gpio
    name: "Dehumidifier Relay"
    pin: GPIO12
    id: relay
    on_turn_off:
      - delay: 15s
      - switch.turn_on: relay

status_led:
  pin:
    number: GPIO13
    inverted: true

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "Dehumidifier Current"
    voltage:
      name: "Dehumidifier Voltage"
    power:
      name: "Dehumidifier Power"
      id: my_power

  - platform: total_daily_energy
    name: "Dehumidifier Total Daily Energy"
    power_id: my_power

  - platform: uptime
    name: "Dehumidifier Uptime"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: 'America/New_York'

text_sensor:
  - platform: version
    name: "Dehumidifier ESPHome Version"
